---
  # Staging machines should be provisioned with local code,
  # rather than pulling down stable releases from the app code.
  # Therefore build the local debs before provisioning the staging hosts.
- include: build-deb-pkgs.yml
  when: "install_local_packages"

- name: Add FPF apt repository and install base packages.
  hosts: staging
  pre_tasks:
    - name: Extract ec2 vars when in AWS
      ec2_facts:
      when: amazon_builder
      tags: reboot
  roles:
    - { role: common, tags: common }
    - { role: tor-hidden-services, tags: tor }
    - { role: install-fpf-repo, tags: [fpfrepo] }
    - { role: grsecurity, when: grsecurity, tags: [grsec, grsecurity] }
    - { role: install-local-packages, tags: [install_local_packages, rebuild],
        when: install_local_packages }
  sudo: yes

- name: Configure OSSEC manager.
  hosts: mon-staging
  roles:
    - { role: ossec-server, tags: [ ossec, ossec_server ] }
  sudo: yes

- name: Configure SecureDrop Application Server.
  hosts: app-staging
  roles:
    - { role: ossec-agent, tags: [ ossec, ossec_agent ] }
    - { role: app, tags: app }
    - { role: app-test, tags: app-test }
    - role: backup
      # By default backups will NOT run, since they can claim a substantial
      # amount of disk space. Enable backups explicitly via a backup var, or
      # implicitly if performing a restore.
      when: (perform_backup is defined and perform_backup == true) or
            (restore_file is defined and restore_file != '')
      tags: backup
  sudo: yes

  # Set iptables rules with exemptions for staging that permit direct access for SSH.
  # The overrides that permit direct access are managed in group_vars/staging.yml,
  # and default false in production environments, in order to force SSH traffic over Tor.
- name: Configure host firewalls (with direct access for staging).
  hosts: staging
  roles:
    - { role: restrict-direct-access, tags: [ common, restrict-direct-access ] }
  sudo: yes
